### ISSUE TITLE
1.6.0 crash on 1.20.1 but mark as 1.20.1 on modrinth

### ISSUE THREAD

**Issue by SettingDust** [theendercore/VisibleToggleSprintMulti#1]
```
java.lang.NoSuchMethodError: 'net.minecraft.class_340 net.minecraft.class_329.method_53531()'
	at com.theendercore.visible_toggle_sprint.common.HudRender.renderHud(HudRender.java:29)
	at com.theendercore.visible_toggle_sprint.platform.FabricPlatformHelper.lambda$register$0(FabricPlatformHelper.java:37)
	at net.fabricmc.fabric.api.client.rendering.v1.HudRenderCallback.lambda$static$0(HudRenderCallback.java:27)
	at net.minecraft.class_329.handler$chd001$fabric-rendering-v1$render(class_329.java:7386)
	at net.minecraft.class_329.method_1753(class_329.java:370)
	at net.minecraft.class_757.method_3192(class_757.java:926)
	at net.minecraft.class_310.method_1523(class_310.java:1219)
	at net.minecraft.class_310.method_1514(class_310.java:802)
	at net.minecraft.client.main.Main.main(Main.java:250)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:87)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:130)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70)
```

**Comment by theendercore** [comment]
My bad. I don't know how That's the only place where I added that.
